### ISSUE TITLE
deploy script: ssh_init: Network error: Cannot assign requested address

### ISSUE THREAD

**Issue by ITCMD** [stjeong/rasp_vusb#4]
On running the deploy_with_pscp.bat script, I get the following response:
```
deploy_with_pscp.bat 192.168.1.34
ssh_init: Network error: Cannot assign requested address
Error occurred!
G:\GitHub\rasp_vusb\script>

```.
I am able to ssh into the pi at 192.168.1.34

**Comment by stjeong** [comment]
You have to solve the problem by yourself. That script uploads the file just using pscp.exe, which means your pscp.exe is not working now. You can test it with "pscp testfile.txt pi@192.168.1.34:/share". That script must be working.

**Comment by ITCMD** [comment]
Okay thank you, any ideas on how to test it and see what's wrong? Does it share config with putty? What exactly does pscp do? I will close this issue in a couple of days

**Comment by stjeong** [comment]
I haven't ever experienced with that. You'd better googled with these keyword "pscp ssh_init: Network error: Cannot assign requested address"

**Comment by The-Drobe** [comment]
I had the same issue you just needed to specify the port with -P 22 in your deploy_with_pscp.bat so it would go from this:



REM In order to run this script, make /share directory in Raspberry PI "sudo mkdir -m 1777 /share"

IF '%1' == '' GOTO ERROR_ARG

SET PIADDR=%1

FOR /F %%I IN ("%0") DO SET CURRENTDIR=%%~dpI

pscp %CURRENTDIR%\*.* pi@%PIADDR%:/share
if errorlevel 1 GOTO ERROR_PSCP

pscp %CURRENTDIR%\..\bin\v1_0_0_1\rasp_vusb_server.out pi@%PIADDR%:/share
if errorlevel 1 GOTO ERROR_PSCP

GOTO END_OF_SCRIPT

:ERROR_ARG
echo deploy_with_pscp [pi_ip_address]
GOTO END_OF_SCRIPT

:ERROR_PSCP
echo Error occurred!

:END_OF_SCRIPT

TO this:



REM In order to run this script, make /share directory in Raspberry PI "sudo mkdir -m 1777 /share"

IF '%1' == '' GOTO ERROR_ARG

SET PIADDR=%1

FOR /F %%I IN ("%0") DO SET CURRENTDIR=%%~dpI

pscp -P 22 %CURRENTDIR%\*.* pi@%PIADDR%:/share
if errorlevel 1 GOTO ERROR_PSCP

pscp -P 22 %CURRENTDIR%\..\bin\v1_0_0_1\rasp_vusb_server.out pi@%PIADDR%:/share
if errorlevel 1 GOTO ERROR_PSCP

GOTO END_OF_SCRIPT

:ERROR_ARG
echo deploy_with_pscp [pi_ip_address]
GOTO END_OF_SCRIPT

:ERROR_PSCP
echo Error occurred!

:END_OF_SCRIPT


I hope that helps

**Comment by stjeong** [comment]
Thanks for sharing your experience. :)
