### ISSUE TITLE
Mouse movement not working with Linux Systems

### ISSUE THREAD

**Issue by ghost** [stjeong/rasp_vusb#7]
Hello!

A represent a team of engineers that are enjoying using your application to automate mouse and keyboard on Windows computers. We've discovered that the device doesn't behave similarly when connected to a Linux device (Mouse inputs aren't working). Would you be able to point us in your code where we can begin looking to try to solve this issue on our own? Thanks and take care!

**Comment by stjeong** [comment]
Sorry for that. Because I have no physical device installing Linux, I haven't ever tested it on the environment.

Anyway, for troubleshooting, you have to check triple_usb_device.sh at Line 25 echo command as follows,

https://github.com/stjeong/rasp_vusb/blob/master/script/triple_usb_device.sh#L25

that means HID device report descriptor. If you run that script, mouse and keyboard device will be recognized at Linux. If not, well... you have to modify the descriptor for Linux.

**Comment by maldonadojsm** [comment]
Hello! Thank you for responding. After looking at the current HID device descriptor at https://github.com/stjeong/rasp_vusb/blob/master/script/triple_usb_device.sh#L25, we've encountered two HID describing two mouse devices. Whats the reasoning behind this? Shouldn't there just be one? Thank you!

**Comment by ghost** [comment]
Hello! Thank you for responding. After looking at the current HID device descriptor at https://github.com/stjeong/rasp_vusb/blob/master/script/triple_usb_device.sh#L25, we've encountered two HID describing two mouse devices. Whats the reasoning behind this? Shouldn't there just be one? Thank you!

**Comment by stjeong** [comment]
Because, I failed to make "one" HID device descriptor for mouse report of absolute position and relative position.

At first, I'd like to use this one,

05, 01             USAGE_PAGE (Generic Desktop)
09, 30             USAGE (X)
09, 31             USAGE (Y)
15, 81             LOGICAL_MINIMUM (-127)
25, 7f             LOGICAL_MAXIMUM (127)
75, 08             REPORT_SIZE (8)
95, 02             REPORT_COUNT (2)
81, 06             INPUT (Data, Var, Rel)

05, 01              USAGE_PAGE (Generic Desktop)
09, 30              USAGE (X)
09, 31              USAGE (Y)
15, 00,             LOGICAL_MINIMUM(0)
26, ff, 7f          LOGICAL_MAXIMUM(32767)
75, 10              REPORT_SIZE (16)
95, 02              REPORT_COUNT (2)
81, 02              INPUT (Data, Var, Abs)

for this purpose.

struct mouse_report_t
{
    uint8_t buttons;
    int8_t relX;
    int8_t relY;
    int16_t absX;
    int16_t absY;
};

But, its report can't be recognized. So I have to provide two mouse, one is for absolute position, another is for relative position.

struct mouse_rel_report_t
{
    uint8_t report_id; /* 2 */
    uint8_t buttons;
    int8_t x;
    int8_t y;
};

struct mouse_abs_report_t
{
    uint8_t report_id; /* 3 */
    int16_t x;
    int16_t y;
    int8_t wheel;
};

05, 01  USAGE_PAGE (Generic Desktop)
09, 02  USAGE (Mouse)
a1, 01  COLLECTION (Application)
09, 01      USAGE (Pointer)
a1, 00      COLLECTION (Physical)
85, 02          REPORT_ID (2)
05, 09          USAGE_PAGE (Button)
19, 01          USAGE_MINIMUM (Button 1)
29, 03          USAGE_MAXIMUM (Button 3)
15, 00          LOGICAL_MINIMUM (0)
25, 01          LOGICAL_MAXIMUM (1)
95, 03          REPORT_COUNT (3)
75, 01          REPORT_SIZE (1)
81, 02          INPUT (Data, Var, Abs)
95, 01          REPORT_COUNT (1)
75, 05          REPORT_SIZE (5)
81, 03          INPUT (Cnst, Var, Abs)
05, 01          USAGE_PAGE (Generic Desktop)
09, 30          USAGE (X)
09, 31          USAGE (Y)
15, 81          LOGICAL_MINIMUM (-127)
25, 7f          LOGICAL_MAXIMUM (127)
75, 08          REPORT_SIZE (8)
95, 02          REPORT_COUNT (2)
81, 06          INPUT (Data, Var, Rel)
C0          END_COLLECTION
C0      END_COLLECTION

05, 01  USAGE_PAGE (Generic Desktop)
09, 02  USAGE (Mouse)
a1, 01  COLLECTION (Application)
09, 01      USAGE (Pointer)
a1, 00      COLLECTION (Physical)
85, 03          REPORT_ID (3)
05, 01          USAGE_PAGE (Generic Desktop)
09, 30          USAGE (X)
09, 31          USAGE (Y)
15, 00,         LOGICAL_MINIMUM(0)
26, ff, 7f      LOGICAL_MAXIMUM(32767)
75, 10          REPORT_SIZE (16)
95, 02          REPORT_COUNT (2)
81, 02          INPUT (Data, Var, Abs)
09, 38          USAGE (Wheel)
15, 81          LOGICAL_MINIMUM (-127)
25, 7f          LOGICAL_MAXIMUM (127)
75, 08          REPORT_SIZE (8)
95, 01          REPORT_COUNT (1)
81, 06          INPUT (Data, Var, Rel)
C0          END_COLLECTION
C0      END_COLLECTION

Can you make the one descriptor?

**Comment by stjeong** [comment]
Expired. (Please open new issue later)
